services:

  ollama:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    container_name: ollama
    volumes:
      - ./srv/ssd/homeserver-mcp/ollama:/root/.ollama
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - mcp-internal
      - mcp-internet

  homeserver_mcp:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: homeserver-mcp
    ports:
      - "8000:8000"
    volumes:
      - ./srv/ssd/homeserver-mcp/root:/mcp
    env_file:
      - .env
    depends_on:
      - ollama
    restart: unless-stopped
    networks:
      - caddy-proxy
      - mcp-internal

  paperless-mcp:
    build:
      context: services/paperless-mcp
      dockerfile: Dockerfile
    container_name: paperless-mcp
    command: ["node", "build/index.js",  "--baseUrl", "${PAPERLESS_URL}", "--token", "${PAPERLESS_API_TOKEN}", "--http", "--port", "3000", "--no-auth"]
    expose:
      - "3000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - mcp-internal
      - mcp-internet

  memos_mcp:
    build:
      context: .
      dockerfile: services/memos/Dockerfile
    container_name: memos-mcp
    volumes:
      - ./srv/ssd/memos/data/memos_prod.db:/external-data/memos/memos.db:ro
      - ./srv/ssd/homeserver-mcp/memos:/mcp
    env_file:
      - .env
    depends_on:
      - ollama
    restart: unless-stopped
    networks:
      - mcp-internal

networks:
  caddy-proxy:
    external: true
  mcp-internal:
    internal: true
  mcp-internet:
